package dev.journey.domain

/**
 * A famous real or fictional route that users can choose to travel, defined by its total
 * distance and the Landmarks along it.
 *
 * A Journey is a distance with ordered Landmarks, not a mapped route — see ADR-0002. It has
 * no coordinates and no polyline, which is what lets a fictional route and a real trail use
 * one model.
 */
data class Journey(
    val id: String,
    val name: String,
    val subtitle: String,
    val totalMetres: Long,
    /**
     * Who wrote this Journey's entries. Required, and shown.
     *
     * Voice is deliberately per-Journey rather than a single house style, so that readers can
     * come to prefer particular writers. That only works if the writer is visible — unattributed
     * variation in tone reads as carelessness, not personality.
     */
    val author: Author,
    val about: About,
    val landmarks: List<Landmark>,
    val ending: Ending,
) {
    init {
        require(landmarks.isNotEmpty()) { "A Journey needs Landmarks" }
        require(landmarks.zipWithNext().all { (a, b) -> a.metresFromStart <= b.metresFromStart }) {
            "Landmarks must be ordered by distance from start"
        }
    }

    /** The next Landmark strictly ahead of [metres], or null once they are all behind you. */
    fun nextAfter(metres: Long): Landmark? = landmarks.firstOrNull { it.metresFromStart > metres }

    /** Everything reached at [metres], nearest first — the view looking back down the trail. */
    fun reachedAt(metres: Long): List<Landmark> =
        landmarks.filter { it.metresFromStart <= metres }.reversed()

    fun isComplete(metres: Long): Boolean = metres >= totalMetres
}

/** Whoever wrote a Journey's entries, credited on the Journey and on what they wrote. */
data class Author(
    val name: String,
    /** A line about them, shown on the Journey overview. */
    val bio: String,
)

/**
 * Somewhere to read more, and the source the claim came from — one field doing both jobs.
 *
 * Required on every Landmark. A writer may pick their own tone, but they may not decline to say
 * where the facts came from.
 */
data class Source(
    val title: String,
    val url: String,
)

/**
 * The Journey overview: what this route is, and why it is in the catalogue.
 *
 * Reached from the Trail header, because it describes the whole line rather than a point on it.
 */
data class About(
    val background: String,
    /** Why this route was chosen. Editorial, and deliberately in the author's voice. */
    val whyThisOne: String,
    val sources: List<Source>,
)

/**
 * What the user reads on finishing a Journey.
 *
 * Authored per Journey rather than generated by the app, because the right note to end on is not
 * the same everywhere — a Roman frontier earns a quiet full stop, and another route might not.
 * There is deliberately no celebration: no confetti, no score, no "well done".
 */
data class Ending(
    val id: String,
    val title: String,
    val body: String,
    val sources: List<Source>,
)

/**
 * A named point on a Journey, positioned at a fixed distance from its start.
 *
 * A Landmark is *reached* when an Expedition's distance passes it, and *read* once the user
 * has seen its entry. Those two states live on the Expedition, not here — this is content,
 * and it is identical for every user.
 */
data class Landmark(
    val id: String,
    val name: String,
    /** Where it sits on the Journey. Positions on real trails are interpolated; see the research. */
    val metresFromStart: Long,
    /** One line shown in the trail list, before you open it. */
    val standfirst: String,
    /** The entry itself. This is the payoff the whole reward loop exists to deliver. */
    val body: String,
    /** Where the facts came from, and where to go next. Required — see [Source]. */
    val sources: List<Source>,
    /** True where the place is a short detour from the route rather than on it. */
    val offRoute: Boolean = false,
) {
    init {
        require(sources.isNotEmpty()) { "$id has no sources; every Landmark must cite its facts" }
    }
}
